
# For more information on how to configure this file, please see:
# https://docs.getdbt.com/docs/profile

unit_test_dbt:
  outputs:
    dev:
      type: postgres
      threads: 1
      host: localhost
      port: 5433
      user: sde
      pass: password
      dbname: devWarehouse
      schema: startdataengg
    prod:
      type: postgres
      threads: 1
      host: localhost
      port: 5432
      user: sde
      pass: password
      dbname: prodWarehouse
      schema: startdataengg
  target: dev
